### PR TITLE
Change how buttons look a bit

### PR DESCRIPTION
**Pull request by BaliDoggo**
i want it to be a bit easier on the eyes

### CODE REVIEW

**Comment by StrongSand94191** [comment]
### The grey text is too hard to read, both the border and the text should be white.

Screenshot 2023-11-06 153139

> How it normally looks

Screenshot 2023-11-06 152958

> How it would look with grey text and white borders (Shaler's idea)

Screenshot 2023-11-06 153058

> How it would look with white text and white borders (My version of Shaler's idea)

**Review by StrongSand94191 — CHANGES_REQUESTED** [review]
### The grey text is too hard to read, both the border and the text should be white.

Screenshot 2023-11-06 153139

> How it normally looks

Screenshot 2023-11-06 152958

> How it would look with grey text and white borders (Shaler's idea)

Screenshot 2023-11-06 153058

> How it would look with white text and white borders (My version of Shaler's idea)
I implemented these changes in #13 Button Patch 2, so you can just approve that PR if you want

**Comment by BaliDoggo** [comment]
I like it

**Comment by BaliDoggo** [comment]
I’ll merge yours

**Pull request closed without merging**
